### PR TITLE
PHP 8.1 fix deprecated null parameters

### PR DESCRIPTION
**Pull request by gigerIT**
fix #186 ($string) of type string is deprecated in PHP 8.1

### CODE REVIEW

**Review by gigerIT — COMMENTED** [review]
fix DOMDocument::__construct(): Passing null to parameter #2 ($encoding) of type string is deprecated in vendor/spatie/array-to-xml/src/ArrayToXml.php on line 29

**Comment by freekmurze** [comment]
Thanks!

**Comment by vasanthanand** [comment]
Is it possible to update this fix to 2.8.1 as well because of version conflics between php 7.4 and php 8.1.
In php 7.4 still the issue is there and because of other dependencies we are unable to update it to php 8.
Thank you so much in advance

**Comment by vasanthanand** [comment]
@freekmurze

**Comment by weirdan** [comment]
@vasanthanand the fix was backported to 2.x and is released in [2.17.0](https://github.com/spatie/array-to-xml/releases/tag/2.17.0)

**Pull request merged**
