### PR TITLE
Ability to add processing instructions

### PR DESCRIPTION
**Pull request by prestonholt**
I came across this issue #143 and also needed this feature. It adds the method `addProcessingInstruction($target, $data)` to the `ArrayToXML` object and can be used like this:

```php
$arrayToXml = new ArrayToXml($array);
$arrayToXml->addProcessingInstruction('qbxml', 'version="13.0"');
$result = $arrayToXml->toXml();
```
Which would generate:
```xml
<?xml version="1.0"?>
<?qbxml version="13.0"?>
<root><Good_guy><name>Luke Skywalker</name><weapon>Lightsaber</weapon></Good_guy><Bad_guy><name>Sauron</name><weapon>Evil Eye</weapon></Bad_guy></root>
```

Multiple processing instructions can be added, and they will always be prepended above the root element.

I figured this may not be used enough to justify adding it to the `convert()` method arguments, but am happy to add it there if wanted.

### CODE REVIEW

**Comment by prestonholt** [comment]
Hey @freekmurze , just wanted to see if you had any feedback on this. Thanks!

**Comment by freekmurze** [comment]
Could you rebase against master to resolve the conflicts?

**Comment by prestonholt** [comment]
@freekmurze Conflicts should be resolved now

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
