### PR TITLE
fixing typo

### PR DESCRIPTION
**Pull request by riotera**

### CODE REVIEW

**Comment by freekmurze** [comment]
Hi, thanks for your contribution.

This PR does much more than just fixing a typo. It also contains a breaking change for people who might have set `$replaceSpacesByUnderScoresInKeyNames` to false. That's why I won't be able to pull it.

**Comment by riotera** [comment]
Hi,

sorry I messed up the pull request. I sent another pull request only with the typo :)

About the new parameter $options, I added it to configure mainly the XML encoding, it's important for me and others the UTF-8. The $options parameter can be added after `$replaceSpacesByUnderScoresInKeyNames` if you think it's a good solution and you agree about the encoding.

**Comment by freekmurze** [comment]
No worries, I'm grateful to you submitted the typo in a seperate PR.

I agree on adding `$options` after `$replaceSpacesByUnderScoresInKeyNames`, so if you send me another new PR, I'd probably merge it.

**Comment by freekmurze** [comment]
Reopen when you've finished this PR.

**Pull request closed without merging**
